site_name: CGMSIM documentation

theme:
  name: material
  highlightjs: true
  logo: 'logo.png'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: deep orange
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  font:
    text: Roboto

extra_javascript:
  - javascript/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    #- stylesheets/admonitions.css
    - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lsandini
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kinkkuporsas
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/lsandini"  target="_blank" rel="noopener">CGMSIM team</a>

nav:
- Home: 
    - Introduction: 'index.md'
- Admin Panel:
    - Login: 
        - Fitbit: 'admin/login/fitbit.md'
        - Google: 'admin/login/google.md'
        - Local user: 'admin/login/local.md'

    - Profile: 
        - Preprofile: 'admin/profile/preprofile.md'
        - Profile (desktop): 'admin/profile/profile.md'
        - Profile (mobile): 'admin/profile/profile-mobile.md' 

    - Create Nightscout: 'admin/create-nightscout.md'
    - Subject: 'admin/subject.md'
    - Parameters: 'admin/parameters.md'
    - Kickstart: 'admin/kickstart.md'
    - Activate: 'admin/activate.md'

- Nightscout: 
    - Profile: 'nightscout/profile.md'
    - Treatments: 'nightscout/treatments.md'
    - Activity: 'nightscout/activity.md'
    - Pump mode: 'nightscout/pump-mode.md'

- Mathematical models:
    - CGMSIM:  
        - Overview: 'model/overview.md'  
        - Mealtime insulin: 'model/mealtime.md'
        - Long-acting Agonists: 'model/la-agonists.md'
        - Carbs: 'model/food.md'
        - Endogenous Glucose Production: 'model/liver.md'
        - Physical Activity: 'model/physical.md'
        - Random Effects: 'model/random.md'
    - UVA/Padova: 'model/uva-padova.md'

- Contact: 
    - Contact: 'contact/contact.md'



