site_name: CGMSIM documentation

theme:
  name: material
  highlightjs: true
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: deep orange
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  font:
    text: Roboto

extra_javascript:
  - javascript/extra.js
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    #- stylesheets/admonitions.css
    - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lsandini
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kinkkuporsas
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - toc:
      permalink: true
      title: On this page

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/lsandini"  target="_blank" rel="noopener">CGMSIM team</a>

nav:
- Home: 
    - index.md
- Admin Panel:
    - Login: 
        - Fitbit: admin/login/fitbit.md
        - Google: admin/login/google.md
        - Local: admin/login/local.md

    - Profile: 
        - Pre-profile: admin/profile/preprofile.md
        - Desktop Profile: admin/profile/profile-desktop.md
        - Mobile Profile: admin/profile/profile-mobile.md
        - Create Nightscout: admin/create-nightscout.md
        - Define Subject: admin/subject.md
        - CGMSIM parameters: admin/parameters.md
        - Kickstart: admin/kickstart.md
        - Activate: admin/activate.md

- Nightscout: 
    - nightscout/profile.md
    - nightscout/meals.md
    - nightscout/la-agonists.md
    - nightscout/activity.md
    - nightscout/pump-mode.md

- Mathematical models:
    - CGMSIM:  
        - Overview: 'model/overview.md'  
        - Mealtime insulin: 'model/mealtime.md'
        - Long-acting Agonists: 'model/la-agonists.md'
        - Carbs: 'model/food.md'
        - Endogenous Glucose Production: 'model/liver.md'
        - Physical Activity: 'model/physical.md'
        - Random Effects: 'model/random.md'
    - UVA/Padova: 'model/uva-padova.md'

- Contact: 
    - Contact: 'contact/contact.md'
